apiVersion: v1
kind: Secret
metadata:
  name: hdim-db-credentials
  labels:
    app.kubernetes.io/part-of: hdim-platform
type: Opaque
stringData:
  POSTGRES_USER: healthdata
  POSTGRES_PASSWORD: demo_password_2024
  POSTGRES_DB: healthdata_db
  SPRING_DATASOURCE_USERNAME: healthdata
  SPRING_DATASOURCE_PASSWORD: demo_password_2024
---
apiVersion: v1
kind: Secret
metadata:
  name: hdim-redis-credentials
  labels:
    app.kubernetes.io/part-of: hdim-platform
type: Opaque
stringData:
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: hdim-kafka-credentials
  labels:
    app.kubernetes.io/part-of: hdim-platform
type: Opaque
stringData:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
---
apiVersion: v1
kind: Secret
metadata:
  name: hdim-jwt-credentials
  labels:
    app.kubernetes.io/part-of: hdim-platform
type: Opaque
stringData:
  JWT_SECRET: DemoSecretKeyForHDIMShouldBeAtLeast256BitsLongForHS256Algorithm12345678
  HEALTHDATA_SECURITY_JWT_SECRET: DemoSecretKeyForHDIMShouldBeAtLeast256BitsLongForHS256Algorithm12345678
  GATEWAY_AUTH_SIGNING_SECRET: "2J3YcbuHgPp0xyMq3GHYJ/MNolqB+Hvp4j/fsA6LQYM="
---
apiVersion: v1
kind: Secret
metadata:
  name: hdim-gateway-db
  labels:
    app.kubernetes.io/part-of: hdim-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gateway_db
  SPRING_DATASOURCE_USERNAME: healthdata
  SPRING_DATASOURCE_PASSWORD: demo_password_2024
