apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hdim-demo

resources:
  - namespace.yaml
  - config/
  - infrastructure/
  - gateways/
  - services/
  - frontend/
  - observability/
  - ops/
  - ingress/
