import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("org.springframework.boot") version "3.3.5"
    id("io.spring.dependency-management") version "1.1.6"
    kotlin("jvm") version "1.9.20"
    kotlin("plugin.spring") version "1.9.20"
    kotlin("plugin.jpa") version "1.9.20"
}

group = "com.healthdata"
version = "2.0.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.spring.io/milestone") }
}

dependencies {
    // Spring Boot Core
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-cache")

    // Spring Modulith - The Key to Modular Monolith
    implementation("org.springframework.modulith:spring-modulith-starter-core:1.2.0")
    implementation("org.springframework.modulith:spring-modulith-starter-jpa:1.2.0")
    implementation("org.springframework.modulith:spring-modulith-events-core:1.2.0")
    implementation("org.springframework.modulith:spring-modulith-runtime:1.2.0")

    // Database
    implementation("org.postgresql:postgresql:42.7.4")
    implementation("org.liquibase:liquibase-core:4.29.2")

    // HAPI FHIR (simplified for compatibility)
    implementation("ca.uhn.hapi.fhir:hapi-fhir-base:6.10.0")
    implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.10.0")

    // CQL Engine (commented out for now - add after base build works)
    // implementation("org.opencds.cqf.cql:engine:2.4.0")
    // implementation("org.opencds.cqf.cql:engine-fhir:2.4.0")

    // Caching
    implementation("com.github.ben-manes.caffeine:caffeine:3.1.8")

    // JWT
    implementation("io.jsonwebtoken:jjwt-api:0.12.6")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.12.6")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.12.6")

    // Email
    implementation("org.springframework.boot:spring-boot-starter-mail")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")

    // WebSocket for real-time updates
    implementation("org.springframework.boot:spring-boot-starter-websocket")

    // Monitoring
    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.micrometer:micrometer-tracing-bridge-otel")

    // Documentation
    // Disabled for compatibility with Spring Boot 3.3.5 - uses incompatible LiteWebJarsResourceResolver
    // implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0")

    // Utilities
    implementation("org.apache.commons:commons-lang3:3.17.0")
    implementation("com.google.guava:guava:33.3.1-jre")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")

    // Lombok
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    // Development
    developmentOnly("org.springframework.boot:spring-boot-devtools")

    // Testing
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.modulith:spring-modulith-starter-test:1.2.0")
    testImplementation("org.springframework.security:spring-security-test")
    testImplementation("org.testcontainers:testcontainers:1.19.0")
    testImplementation("org.testcontainers:postgresql:1.19.0")
    testImplementation("org.testcontainers:junit-jupiter:1.19.0")
    testImplementation("io.mockk:mockk:1.13.8")
    testImplementation("com.ninja-squad:springmockk:4.0.2")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs += "-Xjsr305=strict"
        jvmTarget = "21"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}

// Spring Boot Native Configuration
tasks.bootBuildImage {
    imageName.set("healthdata/platform:${version}")
    environment.set(mapOf(
        "BP_NATIVE_IMAGE" to "true",
        "BP_JVM_VERSION" to "21"
    ))
}

// Modulith Documentation Generation
tasks.register("generateModulithDocs") {
    doLast {
        println("Generating Modulith architecture documentation...")
        // This will be auto-generated by Spring Modulith
    }
}