#!/bin/bash
# =============================================================================
# HDIM Customer Simulation Setup Script
# =============================================================================
# This script sets up the complete customer simulation environment including:
# - External PostgreSQL databases
# - External HAPI FHIR server with sample data
# - HDIM minimal clinical portal services
#
# Prerequisites:
# - Docker and Docker Compose installed
# - Ports 5432, 8080, 8001, 8084-8087, 4200, 6379, 16686 available
#
# Usage:
#   chmod +x scripts/setup-customer-simulation.sh
#   ./scripts/setup-customer-simulation.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_DIR"

echo "========================================"
echo "HDIM Customer Simulation Setup"
echo "========================================"
echo ""

# =============================================================================
# STEP 1: Setup Environment File
# =============================================================================
echo "[1/6] Setting up environment configuration..."

if [ ! -f .env ]; then
    cp .env.customer-simulation .env
    echo "  Created .env from .env.customer-simulation"
fi

# Update .env with required settings
cat > .env << 'EOF'
# HDIM Customer Simulation Environment
# Generated by setup-customer-simulation.sh

# ==============================================================================
# EXTERNAL POSTGRESQL
# ==============================================================================
POSTGRES_HOST=host.docker.internal
POSTGRES_PORT=5432
POSTGRES_USER=healthdata
POSTGRES_PASSWORD=healthdata_password
POSTGRES_DB=healthdata_db

# ==============================================================================
# EXTERNAL FHIR SERVER
# ==============================================================================
EXTERNAL_FHIR_URL=http://host.docker.internal:8080/fhir
FHIR_AUTH_TYPE=none

# ==============================================================================
# SERVICE VERSIONS
# ==============================================================================
VERSION=latest

# ==============================================================================
# AUTHENTICATION
# ==============================================================================
GATEWAY_AUTH_DEV_MODE=true
GATEWAY_AUTH_SIGNING_SECRET=dev-signing-secret-for-local-testing-only-minimum-32-chars
JWT_SECRET=hdim-dev-jwt-secret-key-for-local-development-only-64chars
JWT_EXPIRATION_MS=900000

# ==============================================================================
# REDIS (Docker)
# ==============================================================================
REDIS_HOST=redis
REDIS_PORT=6379

# ==============================================================================
# TRACING (Jaeger)
# ==============================================================================
OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

# ==============================================================================
# DEMO OPTIONS
# ==============================================================================
DEMO_AUTO_SEED=false
DEMO_MODE_ENABLED=false
DEMO_TENANT_ID=demo-tenant
EOF

echo "  Environment file configured"

# =============================================================================
# STEP 2: Start External PostgreSQL
# =============================================================================
echo ""
echo "[2/6] Starting external PostgreSQL..."

# Check if postgres container exists
if docker ps -a --format '{{.Names}}' | grep -q '^hdim-external-postgres$'; then
    echo "  PostgreSQL container exists, starting..."
    docker start hdim-external-postgres 2>/dev/null || true
else
    echo "  Creating new PostgreSQL container..."
    docker run -d \
        --name hdim-external-postgres \
        -e POSTGRES_USER=healthdata \
        -e POSTGRES_PASSWORD=healthdata_password \
        -e POSTGRES_DB=healthdata_db \
        -p 5432:5432 \
        postgres:15-alpine
fi

# Wait for PostgreSQL to be ready
echo "  Waiting for PostgreSQL to be ready..."
for i in {1..30}; do
    if docker exec hdim-external-postgres pg_isready -U healthdata > /dev/null 2>&1; then
        echo "  PostgreSQL is ready!"
        break
    fi
    sleep 1
done

# =============================================================================
# STEP 3: Create Databases
# =============================================================================
echo ""
echo "[3/6] Creating databases..."

DATABASES=(
    "gateway_db"
    "fhir_db"
    "patient_db"
    "quality_db"
    "caregap_db"
    "cql_db"
    "consent_db"
    "analytics_db"
    "hcc_db"
    "notification_db"
    "ecr_db"
    "cms_db"
    "qrda_db"
    "sdoh_db"
    "predictive_db"
    "prior_auth_db"
    "approval_db"
    "cost_db"
    "docs_db"
    "event_router_db"
    "event_processing_db"
    "ehr_connector_db"
    "demo_db"
    "sales_db"
    "agent_builder_db"
    "agent_runtime_db"
)

for db in "${DATABASES[@]}"; do
    docker exec hdim-external-postgres psql -U healthdata -d healthdata_db -c "CREATE DATABASE $db;" 2>/dev/null || true
done

echo "  Created ${#DATABASES[@]} databases"

# Add pg_trgm extension to key databases
echo "  Adding pg_trgm extension..."
for db in gateway_db fhir_db patient_db quality_db caregap_db; do
    docker exec hdim-external-postgres psql -U healthdata -d $db -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;" 2>/dev/null || true
done

# =============================================================================
# STEP 4: Create Test Users in Gateway DB
# =============================================================================
echo ""
echo "[4/6] Creating test users..."

docker exec hdim-external-postgres psql -U healthdata -d gateway_db << 'EOSQL'
-- Create users table if not exists
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create user_roles table
CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID REFERENCES users(id),
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role)
);

-- Create user_tenants table
CREATE TABLE IF NOT EXISTS user_tenants (
    user_id UUID REFERENCES users(id),
    tenant_id VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_id, tenant_id)
);

-- Create refresh_tokens table
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert test users (password: password123 - BCrypt hash)
INSERT INTO users (username, email, password_hash, first_name, last_name)
VALUES
    ('test_admin', 'admin@hdim-demo.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/9n78H1rkGk1uVz.NmyMKC', 'Admin', 'User'),
    ('test_evaluator', 'evaluator@hdim-demo.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/9n78H1rkGk1uVz.NmyMKC', 'Evaluator', 'User'),
    ('demo_admin', 'demo@demo-tenant.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/9n78H1rkGk1uVz.NmyMKC', 'Demo', 'Admin')
ON CONFLICT (username) DO NOTHING;

-- Assign roles
INSERT INTO user_roles (user_id, role)
SELECT id, 'ADMIN' FROM users WHERE username = 'test_admin'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role)
SELECT id, 'EVALUATOR' FROM users WHERE username = 'test_evaluator'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role)
SELECT id, 'ADMIN' FROM users WHERE username = 'demo_admin'
ON CONFLICT DO NOTHING;

-- Assign tenants
INSERT INTO user_tenants (user_id, tenant_id)
SELECT id, 'demo-tenant' FROM users WHERE username IN ('test_admin', 'test_evaluator', 'demo_admin')
ON CONFLICT DO NOTHING;

INSERT INTO user_tenants (user_id, tenant_id)
SELECT id, 'demo-tenant' FROM users WHERE username = 'test_admin'
ON CONFLICT DO NOTHING;
EOSQL

echo "  Test users created"

# =============================================================================
# STEP 5: Start External HAPI FHIR Server
# =============================================================================
echo ""
echo "[5/6] Starting external HAPI FHIR server..."

# Remove existing container if any
docker rm -f external-fhir-server 2>/dev/null || true

# Start HAPI FHIR with in-memory H2
docker run -d \
    --name external-fhir-server \
    -p 8080:8080 \
    -e hapi.fhir.fhir_version=R4 \
    -e hapi.fhir.allow_external_references=true \
    -e hapi.fhir.allow_multiple_delete=true \
    -e spring.datasource.url=jdbc:h2:mem:hapi \
    -e spring.datasource.driverClassName=org.h2.Driver \
    -e spring.jpa.hibernate.ddl-auto=update \
    -e JAVA_TOOL_OPTIONS="-Xms512m -Xmx2g" \
    hapiproject/hapi:latest

echo "  HAPI FHIR server starting (takes ~2 minutes)..."
echo "  You can check status with: curl http://localhost:8080/fhir/metadata"

# =============================================================================
# STEP 6: Start HDIM Clinical Portal Services
# =============================================================================
echo ""
echo "[6/6] Starting HDIM clinical portal services..."

docker compose -f docker-compose.minimal-clinical.yml up -d

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Services starting up. Check status with:"
echo "  docker ps --filter 'name=hdim'"
echo ""
echo "Service URLs (after startup ~2-3 minutes):"
echo "  - Clinical Portal:    http://localhost:4200"
echo "  - Gateway API:        http://localhost:8001"
echo "  - FHIR Service:       http://localhost:8085/fhir"
echo "  - Patient Service:    http://localhost:8084/patient"
echo "  - Quality Measure:    http://localhost:8087/quality-measure"
echo "  - Care Gap:           http://localhost:8086/care-gap"
echo "  - External FHIR:      http://localhost:8080/fhir"
echo "  - Jaeger Tracing:     http://localhost:16686"
echo ""
echo "Test Users (password: password123):"
echo "  - test_admin / admin@hdim-demo.com (ADMIN)"
echo "  - test_evaluator / evaluator@hdim-demo.com (EVALUATOR)"
echo "  - demo_admin / demo@demo-tenant.com (ADMIN)"
echo ""
echo "To load sample FHIR data after HAPI FHIR is ready:"
echo "  ./scripts/load-sample-fhir-data.sh"
echo ""
