/**
 * Comprehensive service definitions for HDIM platform
 * Based on SERVICE_CATALOG.md - 51+ microservices
 *
 * This file defines all services, ports, categories, and metadata
 * for display in the Admin Portal Service Dashboard.
 */

export interface ServiceDefinitionMetadata {
  id: string;
  name: string;
  displayName: string;
  port: number | null;
  category: ServiceCategory;
  purpose: string;
  techStack: string[];
  healthEndpoint: string | null;
  metricsEndpoint: string | null;
  logsEndpoint: string | null;
  grafanaDashboard: string | null;
  documentationUrl: string;
  dependencies: string[];
}

export type ServiceCategory =
  | 'Core Clinical'
  | 'Analytics & Reporting'
  | 'Risk & Cost'
  | 'Workflow & Authorization'
  | 'Integration & Data'
  | 'Platform & Infrastructure'
  | 'AI & Advanced'
  | 'Event Services'
  | 'Infrastructure';

export const SERVICE_DEFINITIONS: ServiceDefinitionMetadata[] = [
  // =====================
  // Core Clinical Services
  // =====================
  {
    id: 'quality-measure-service',
    name: 'quality-measure-service',
    displayName: 'Quality Measure Service',
    port: 8087,
    category: 'Core Clinical',
    purpose: 'HEDIS measures, quality calculations, CQL evaluation',
    techStack: ['Spring Boot', 'PostgreSQL', 'Redis', 'Kafka'],
    healthEndpoint: 'http://localhost:8087/actuator/health',
    metricsEndpoint: 'http://localhost:8087/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/quality-measure',
    documentationUrl: '/docs/services/quality-measure-service',
    dependencies: ['postgresql', 'redis', 'kafka', 'patient-service', 'cql-engine-service'],
  },
  {
    id: 'patient-service',
    name: 'patient-service',
    displayName: 'Patient Service',
    port: 8084,
    category: 'Core Clinical',
    purpose: 'Patient demographics, registries, care team management',
    techStack: ['Spring Boot', 'PostgreSQL', 'Redis'],
    healthEndpoint: 'http://localhost:8084/actuator/health',
    metricsEndpoint: 'http://localhost:8084/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/patient-service',
    documentationUrl: '/docs/services/patient-service',
    dependencies: ['postgresql', 'redis'],
  },
  {
    id: 'cql-engine-service',
    name: 'cql-engine-service',
    displayName: 'CQL Engine Service',
    port: 8081,
    category: 'Core Clinical',
    purpose: 'CQL expression evaluation, clinical logic processing',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: 'http://localhost:8081/actuator/health',
    metricsEndpoint: 'http://localhost:8081/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/cql-engine',
    documentationUrl: '/docs/services/cql-engine-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'fhir-service',
    name: 'fhir-service',
    displayName: 'FHIR Service',
    port: 8085,
    category: 'Core Clinical',
    purpose: 'FHIR R4 resource management, clinical documents',
    techStack: ['Spring Boot', 'HAPI FHIR', 'PostgreSQL', 'Redis'],
    healthEndpoint: 'http://localhost:8085/actuator/health',
    metricsEndpoint: 'http://localhost:8085/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/fhir-service',
    documentationUrl: '/docs/services/fhir-service',
    dependencies: ['postgresql', 'redis'],
  },
  {
    id: 'care-gap-service',
    name: 'care-gap-service',
    displayName: 'Care Gap Service',
    port: 8086,
    category: 'Core Clinical',
    purpose: 'Care gap detection, closure recommendations, bulk operations',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka'],
    healthEndpoint: 'http://localhost:8086/actuator/health',
    metricsEndpoint: 'http://localhost:8086/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/care-gap-service',
    documentationUrl: '/docs/services/care-gap-service',
    dependencies: ['postgresql', 'kafka', 'patient-service', 'quality-measure-service'],
  },
  {
    id: 'consent-service',
    name: 'consent-service',
    displayName: 'Consent Service',
    port: 8082,
    category: 'Core Clinical',
    purpose: 'Patient consent management, privacy controls',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: 'http://localhost:8082/actuator/health',
    metricsEndpoint: 'http://localhost:8082/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/consent-service',
    documentationUrl: '/docs/services/consent-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'event-processing-service',
    name: 'event-processing-service',
    displayName: 'Event Processing Service',
    port: null,
    category: 'Core Clinical',
    purpose: 'Event processing pipeline, stream handling',
    techStack: ['Spring Boot', 'Kafka', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/event-processing-service',
    dependencies: ['kafka', 'postgresql'],
  },

  // =====================
  // Platform & Infrastructure Services
  // =====================
  {
    id: 'gateway-service',
    name: 'gateway-service',
    displayName: 'API Gateway',
    port: 8001,
    category: 'Platform & Infrastructure',
    purpose: 'API gateway, authentication, routing to all services',
    techStack: ['Spring Boot', 'Kong', 'PostgreSQL'],
    healthEndpoint: 'http://localhost:8001/actuator/health',
    metricsEndpoint: 'http://localhost:8001/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/gateway-service',
    documentationUrl: '/docs/services/gateway-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'notification-service',
    name: 'notification-service',
    displayName: 'Notification Service',
    port: null,
    category: 'Platform & Infrastructure',
    purpose: 'Email, SMS, in-app notifications',
    techStack: ['Spring Boot', 'PostgreSQL', 'Redis'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/notification-service',
    dependencies: ['postgresql', 'redis'],
  },
  {
    id: 'audit-service',
    name: 'audit-service',
    displayName: 'Audit Service',
    port: 8093,
    category: 'Platform & Infrastructure',
    purpose: 'Compliance audit logging, user activity tracking',
    techStack: ['Spring Boot', 'PostgreSQL', 'Elasticsearch'],
    healthEndpoint: 'http://localhost:8093/actuator/health',
    metricsEndpoint: 'http://localhost:8093/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/audit-service',
    documentationUrl: '/docs/services/audit-service',
    dependencies: ['postgresql', 'elasticsearch'],
  },
  {
    id: 'event-router-service',
    name: 'event-router-service',
    displayName: 'Event Router Service',
    port: null,
    category: 'Platform & Infrastructure',
    purpose: 'Event routing, topic management, message transformation',
    techStack: ['Spring Boot', 'Kafka'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/event-router-service',
    dependencies: ['kafka'],
  },
  {
    id: 'cdr-processor-service',
    name: 'cdr-processor-service',
    displayName: 'CDR Processor Service',
    port: null,
    category: 'Platform & Infrastructure',
    purpose: 'Clinical Data Repository processing',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/cdr-processor-service',
    dependencies: ['postgresql'],
  },

  // =====================
  // Event Services (Phase 5 - Event Sourcing)
  // =====================
  {
    id: 'patient-event-service',
    name: 'patient-event-service',
    displayName: 'Patient Event Service',
    port: 8110,
    category: 'Event Services',
    purpose: 'Patient events and projections using Event Sourcing',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka', 'Event Store'],
    healthEndpoint: 'http://localhost:8110/actuator/health',
    metricsEndpoint: 'http://localhost:8110/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/patient-event-service',
    documentationUrl: '/docs/services/patient-event-service',
    dependencies: ['postgresql', 'kafka'],
  },
  {
    id: 'quality-measure-event-service',
    name: 'quality-measure-event-service',
    displayName: 'Quality Measure Event Service',
    port: 8191,
    category: 'Event Services',
    purpose: 'Quality measure events and calculations using CQRS',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka', 'Event Store'],
    healthEndpoint: 'http://localhost:8191/actuator/health',
    metricsEndpoint: 'http://localhost:8191/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/quality-measure-event-service',
    documentationUrl: '/docs/services/quality-measure-event-service',
    dependencies: ['postgresql', 'kafka'],
  },
  {
    id: 'care-gap-event-service',
    name: 'care-gap-event-service',
    displayName: 'Care Gap Event Service',
    port: 8111,
    category: 'Event Services',
    purpose: 'Care gap events and detection using Event Sourcing',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka', 'Event Store'],
    healthEndpoint: 'http://localhost:8111/actuator/health',
    metricsEndpoint: 'http://localhost:8111/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/care-gap-event-service',
    documentationUrl: '/docs/services/care-gap-event-service',
    dependencies: ['postgresql', 'kafka'],
  },
  {
    id: 'clinical-workflow-event-service',
    name: 'clinical-workflow-event-service',
    displayName: 'Clinical Workflow Event Service',
    port: 8193,
    category: 'Event Services',
    purpose: 'Clinical workflow events and orchestration',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka', 'Event Store'],
    healthEndpoint: 'http://localhost:8193/actuator/health',
    metricsEndpoint: 'http://localhost:8193/actuator/metrics',
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/clinical-workflow-event-service',
    documentationUrl: '/docs/services/clinical-workflow-event-service',
    dependencies: ['postgresql', 'kafka'],
  },

  // =====================
  // Analytics & Reporting Services
  // =====================
  {
    id: 'analytics-service',
    name: 'analytics-service',
    displayName: 'Analytics Service',
    port: null,
    category: 'Analytics & Reporting',
    purpose: 'Quality reporting, dashboards, KPI calculation',
    techStack: ['Spring Boot', 'PostgreSQL', 'Elasticsearch'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/analytics-service',
    dependencies: ['postgresql', 'elasticsearch'],
  },
  {
    id: 'qrda-export-service',
    name: 'qrda-export-service',
    displayName: 'QRDA Export Service',
    port: null,
    category: 'Analytics & Reporting',
    purpose: 'QRDA I/III export for CMS submission',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/qrda-export-service',
    dependencies: ['postgresql', 'quality-measure-service'],
  },
  {
    id: 'predictive-analytics-service',
    name: 'predictive-analytics-service',
    displayName: 'Predictive Analytics Service',
    port: null,
    category: 'Analytics & Reporting',
    purpose: 'Predictive modeling, ML-based forecasting',
    techStack: ['Spring Boot', 'PostgreSQL', 'TensorFlow'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/predictive-analytics-service',
    dependencies: ['postgresql'],
  },

  // =====================
  // Risk & Cost Management Services
  // =====================
  {
    id: 'hcc-service',
    name: 'hcc-service',
    displayName: 'HCC Service',
    port: null,
    category: 'Risk & Cost',
    purpose: 'HCC risk adjustment, coding optimization',
    techStack: ['Spring Boot', 'PostgreSQL', 'ML Models'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/hcc-service',
    dependencies: ['postgresql', 'patient-service'],
  },
  {
    id: 'cost-monitoring-service',
    name: 'cost-monitoring-service',
    displayName: 'Cost Monitoring Service',
    port: null,
    category: 'Risk & Cost',
    purpose: 'Cost tracking, budget management',
    techStack: ['Spring Boot', 'PostgreSQL', 'Prometheus'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/cost-monitoring-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'risk-stratification-service',
    name: 'risk-stratification-service',
    displayName: 'Risk Stratification Service',
    port: null,
    category: 'Risk & Cost',
    purpose: 'Patient risk scoring, intervention prioritization',
    techStack: ['Spring Boot', 'PostgreSQL', 'ML Models'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/risk-stratification-service',
    dependencies: ['postgresql', 'patient-service'],
  },

  // =====================
  // Workflow & Authorization Services
  // =====================
  {
    id: 'prior-auth-service',
    name: 'prior-auth-service',
    displayName: 'Prior Authorization Service',
    port: null,
    category: 'Workflow & Authorization',
    purpose: 'Prior authorization management, appeal tracking',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/prior-auth-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'approval-service',
    name: 'approval-service',
    displayName: 'Approval Service',
    port: null,
    category: 'Workflow & Authorization',
    purpose: 'Workflow approval engine, task management',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/approval-service',
    dependencies: ['postgresql', 'kafka'],
  },
  {
    id: 'payer-workflows-service',
    name: 'payer-workflows-service',
    displayName: 'Payer Workflows Service',
    port: null,
    category: 'Workflow & Authorization',
    purpose: 'Payer-specific workflows, business process orchestration',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/payer-workflows-service',
    dependencies: ['postgresql', 'kafka'],
  },
  {
    id: 'migration-workflow-service',
    name: 'migration-workflow-service',
    displayName: 'Migration Workflow Service',
    port: null,
    category: 'Workflow & Authorization',
    purpose: 'Patient migration workflows between payers',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/migration-workflow-service',
    dependencies: ['postgresql', 'kafka'],
  },

  // =====================
  // Integration & Data Services
  // =====================
  {
    id: 'ehr-connector-service',
    name: 'ehr-connector-service',
    displayName: 'EHR Connector Service',
    port: null,
    category: 'Integration & Data',
    purpose: 'Electronic Health Record integration, HL7 v2/v3',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/ehr-connector-service',
    dependencies: ['postgresql', 'kafka', 'fhir-service'],
  },
  {
    id: 'data-enrichment-service',
    name: 'data-enrichment-service',
    displayName: 'Data Enrichment Service',
    port: null,
    category: 'Integration & Data',
    purpose: 'Data validation, enrichment, deduplication',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/data-enrichment-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'ecr-service',
    name: 'ecr-service',
    displayName: 'Electronic Case Reporting Service',
    port: null,
    category: 'Integration & Data',
    purpose: 'Electronic Case Reporting for public health',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/ecr-service',
    dependencies: ['postgresql', 'fhir-service'],
  },
  {
    id: 'sdoh-service',
    name: 'sdoh-service',
    displayName: 'Social Determinants of Health Service',
    port: null,
    category: 'Integration & Data',
    purpose: 'Social determinants of health tracking',
    techStack: ['Spring Boot', 'PostgreSQL', 'Redis'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/sdoh-service',
    dependencies: ['postgresql', 'redis', 'patient-service'],
  },
  {
    id: 'documentation-service',
    name: 'documentation-service',
    displayName: 'Documentation Service',
    port: null,
    category: 'Integration & Data',
    purpose: 'Document management, OCR, clinical documentation',
    techStack: ['Spring Boot', 'PostgreSQL', 'S3'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/documentation-service',
    dependencies: ['postgresql', 's3'],
  },

  // =====================
  // AI & Advanced Services
  // =====================
  {
    id: 'ai-assistant-service',
    name: 'ai-assistant-service',
    displayName: 'AI Assistant Service',
    port: null,
    category: 'AI & Advanced',
    purpose: 'AI chatbot, clinical decision support',
    techStack: ['Spring Boot', 'PostgreSQL', 'ML Models'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/ai-assistant-service',
    dependencies: ['postgresql'],
  },
  {
    id: 'agent-runtime-service',
    name: 'agent-runtime-service',
    displayName: 'Agent Runtime Service',
    port: null,
    category: 'AI & Advanced',
    purpose: 'Agent execution engine, autonomous workflows',
    techStack: ['Spring Boot', 'PostgreSQL', 'Kafka'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/agent-runtime-service',
    dependencies: ['postgresql', 'kafka'],
  },
  {
    id: 'agent-builder-service',
    name: 'agent-builder-service',
    displayName: 'Agent Builder Service',
    port: null,
    category: 'AI & Advanced',
    purpose: 'Agent creation and configuration UI',
    techStack: ['Spring Boot', 'PostgreSQL'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/services/agent-builder-service',
    dependencies: ['postgresql'],
  },

  // =====================
  // Infrastructure Services
  // =====================
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    displayName: 'PostgreSQL Database',
    port: 5435,
    category: 'Infrastructure',
    purpose: 'Primary database (29 schemas)',
    techStack: ['PostgreSQL 16'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/postgresql',
    documentationUrl: '/docs/architecture/database',
    dependencies: [],
  },
  {
    id: 'redis',
    name: 'Redis',
    displayName: 'Redis Cache',
    port: 6380,
    category: 'Infrastructure',
    purpose: 'Caching layer (5-minute TTL for HIPAA compliance)',
    techStack: ['Redis 7'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/redis',
    documentationUrl: '/docs/architecture/cache',
    dependencies: [],
  },
  {
    id: 'kafka',
    name: 'Kafka',
    displayName: 'Apache Kafka',
    port: 9094,
    category: 'Infrastructure',
    purpose: 'Event messaging backbone',
    techStack: ['Kafka 3.x'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: 'http://localhost:3001/d/kafka',
    documentationUrl: '/docs/architecture/messaging',
    dependencies: ['zookeeper'],
  },
  {
    id: 'zookeeper',
    name: 'Zookeeper',
    displayName: 'Apache Zookeeper',
    port: 2182,
    category: 'Infrastructure',
    purpose: 'Kafka coordination',
    techStack: ['Zookeeper 3.x'],
    healthEndpoint: null,
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/architecture/messaging',
    dependencies: [],
  },
  {
    id: 'jaeger',
    name: 'Jaeger',
    displayName: 'Jaeger Tracing',
    port: 16686,
    category: 'Infrastructure',
    purpose: 'Distributed tracing UI',
    techStack: ['Jaeger'],
    healthEndpoint: 'http://localhost:16686',
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/guides/distributed-tracing',
    dependencies: [],
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    displayName: 'Prometheus',
    port: 9090,
    category: 'Infrastructure',
    purpose: 'Metrics collection and alerting',
    techStack: ['Prometheus'],
    healthEndpoint: 'http://localhost:9090/-/healthy',
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/guides/monitoring',
    dependencies: [],
  },
  {
    id: 'grafana',
    name: 'Grafana',
    displayName: 'Grafana',
    port: 3001,
    category: 'Infrastructure',
    purpose: 'Metrics visualization and dashboards',
    techStack: ['Grafana'],
    healthEndpoint: 'http://localhost:3001/api/health',
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/guides/monitoring',
    dependencies: ['prometheus'],
  },
  {
    id: 'vault',
    name: 'Vault',
    displayName: 'HashiCorp Vault',
    port: 8200,
    category: 'Infrastructure',
    purpose: 'Secrets management',
    techStack: ['Vault'],
    healthEndpoint: 'http://localhost:8200/v1/sys/health',
    metricsEndpoint: null,
    logsEndpoint: null,
    grafanaDashboard: null,
    documentationUrl: '/docs/guides/security',
    dependencies: [],
  },
];

/**
 * Get services by category
 */
export function getServicesByCategory(category: ServiceCategory): ServiceDefinitionMetadata[] {
  return SERVICE_DEFINITIONS.filter(svc => svc.category === category);
}

/**
 * Get all categories with service counts
 */
export function getCategoriesWithCounts(): { category: ServiceCategory; count: number }[] {
  const categories = Array.from(new Set(SERVICE_DEFINITIONS.map(svc => svc.category)));
  return categories.map(category => ({
    category,
    count: getServicesByCategory(category).length,
  }));
}

/**
 * Get service by ID
 */
export function getServiceById(id: string): ServiceDefinitionMetadata | undefined {
  return SERVICE_DEFINITIONS.find(svc => svc.id === id);
}

/**
 * Get all services with health endpoints
 */
export function getServicesWithHealthEndpoints(): ServiceDefinitionMetadata[] {
  return SERVICE_DEFINITIONS.filter(svc => svc.healthEndpoint !== null);
}
