FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY apps/coaching-ui/nginx.conf /etc/nginx/nginx.conf
COPY dist/apps/coaching-ui .

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:4200/ || exit 1

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
