apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hdim-demo
servers: 1
agents: 0
ports:
  - port: 80:80
    nodeFilters: [loadbalancer]
  - port: 443:443
    nodeFilters: [loadbalancer]
options:
  k3d:
    wait: true
    timeout: 180s
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
