apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fhir-service.yaml
  - patient-service.yaml
  - cql-engine-service.yaml
  - quality-measure-service.yaml
  - care-gap-service.yaml
  - event-processing-service.yaml
  - audit-query-service.yaml
  - hcc-service.yaml
  - demo-seeding-service.yaml
